# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160429_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Channel'),
        ),
        migrations.AlterField(
            model_name='player',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Channel'),
        ),
    ]
